### ISSUE TITLE
Localization issue with report file in combination with test result collection tool

### ISSUE THREAD

**Issue by metaph3r** [MicroFocus/ADM-FT-ToolsLauncher#47]
**Tool**
FTToolsLauncher_net48.exe v1.0 beta (rev.5)

**Describe the bug**

Am I correct with the assumption that the result XML file that is created could/should be used to push the results to ALM Octane using the test result collection tool? It seems that there is a localization issue between the tools.

The FTToolsLauncher uses the locale of the system it runs on. In this case German. For example it saves the run duration with a comma as decimal separator (e.g. time="14,1674812").

The test result collection tool seems to ignore the system localization. This results in an error when trying to push the results to ALM Octane:

**Unable to parse test duration: 14,1674812**

If a change the , to . manually the error disappears.

Also in my point of view it makes no sense to store a localized time in an JUnit result file because this can cause a lot of issues in a CI/CD context.

**To Reproduce**
1. Launch UFT tests with FTToolLauncher (e.g. FTToolsLauncher_net48.exe -paramfile fttoolslauncher.config)
2. Use test result collection tool to send report to ALM Octane (e.g. java -jar test-result-collection-tool.jar -c test-result-collection-tool.conf results.xml)
3. Error message "Unable to parse test duration: 14,1674812" appears

**Expected behavior**
The FTToolsLauncher uses internation localization for the result XML file.

**Screenshots**

**OS and testing tools:**
 - OS: Windows 10 Pro
 - UFT One version: 15.0.2
 - ALM Octane version: 15.1.60.86
 - Test Result Collection Tool: 1.0.13

**Additional context**

**fttoolslauncher.config:**

# Basic parameters
runType=FileSystem
resultsFilename=results.xml

# File System parameters
fsTimeout=3600
Test1=C:\\Develop\\git\\UFT-Flight-Test-Demo\\MyFlight

# Rerun parameters
onCheckFailedTest=true
testType=Rerun only failed tests
Reruns1=1

**test-result-collection-tool.conf**

# Server URL with protocol and port
server=https://octane:8443
# Server sharedspace ID
sharedspace=1001
# Server workspace ID
workspace=2001
# Server username
user=foo
# Server username password
password=bar

**Comment by soleverxu** [comment]
Thank you for raising the issue.
Yes, this might cause a problem when other tools attempt to parse the result file.
We will investigate and try to fix this issue.

**Comment by soleverxu** [comment]
This issue is fixed in FTToolsLauncher `v1.0.22.4723`. Please download the file in the release `v1.0 beta (rev.6)`.
Starting with this version, the number formats are always populated in English language by default and a new parameter `resultFormatLanguage` is introduced to customize the language if necessary. See the README file for more details.

**Comment by metaph3r** [comment]
I can confirm that the issue is closed.
