### ISSUE TITLE
Remove path from test case name

### ISSUE THREAD

**Issue by metaph3r** [MicroFocus/ADM-FT-ToolsLauncher#49]
**Tool**
FTToolsLauncher

**Is your feature request related to a problem? Please describe.**
When running the FTToolsLauncher the resulting XML results file contains the test case name including the full path to the test that was run (e.g. <testcase name="C:\Develop\git\UFT-Flight-Test-Demo\MyFlight"). When uploading the results to Octane using the Test Result Collection Tool the test gets created with that name.

This results in 2 issues. First it looks ugly and second the path might vary depending on the environment the test is run on. So the same test might be created multiple times with different path names.

**Describe the solution you'd like**
The path should be removed from the test case name (e.g. <testcase name="MyFlight") and should only include the name of the UFT test.

**Describe alternatives you've considered**
Maybe a configuration parameter could be added that makes the path optional.

**Environment and testing tools (please complete the following information):**
- OS: Windows 10 Pro
- UFT One version: 15.0.2
- ALM Octane version: 15.1.60.86
- Test Result Collection Tool: 1.0.13

**Comment by soleverxu** [comment]
A new parameter is provided in the `v1.0 beta (rev.7)` that can handle the test name only mode. Please download the executable file in the release page.

**Comment by metaph3r** [comment]
Thanks. It is working as intended.
