### ISSUE TITLE
ReportConverter fails to convert UFT 15.0.2 report

### ISSUE THREAD

**Issue by metaph3r** [MicroFocus/ADM-FT-ToolsLauncher#50]
**Tool**
ReportConverter_net48 v1.0.20.2003

**Describe the bug**
I ran a test using the FTToolsLauncher but also tried it in UFT One GUI. After that test was run the run_results.xml file got created. When trying to use the ReportConverter I get the error message

"Error: The first XML node can't be recognized. The input file is not a valid UFT One test XML report. Res1\Report
The input is invalid."

**To Reproduce**
1. Execute FTToolsLauncher_net48.exe -runType FileSystem -paramfile fttoolslauncher.config
2. Execute ReportConverter_net48.exe -j junit_result.xml MyFlight\Report12 (also tried MyFlight\Report12\run_results.xml)
3. See error

**Expected behavior**
The run result is properly converted.

**OS and testing tools (please complete the following information):**
- OS: Windows 10 Pro (German)
- UFT One version: 15.0.2
- ReportConverter_net48 version: 1.0.20.2003

**Additional context**
Contents of result file:
`<?xml version="1.0"?>
<Results version="1.0">
<ReportNode type="testrun">
<ReportNode type="Action">
<ReportNode type="Step">
<Data>
    <Name>SystemUtil.Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1</Name>
    <StartTime>2021-06-25 11:24:15</StartTime>
    <Result>Done</Result>
    <Extension>
      <IconKey>382e9913f0f4488781f512df7fadc46a</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
    <DeviceInfo />
  </Data>
</ReportNode>
<Data>
    <Name>OpenApp</Name>
    <Description />
    <StartTime>2021-06-25 11:24:14</StartTime>
    <Duration>1</Duration>
    <Result>Done</Result>
    <InputParameters />
    <Extension>
      <IconKey>1e5f548f6ab24bf8b7f8b5978c10bfc9</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
  </Data>
</ReportNode>
<ReportNode type="Action">
<ReportNode type="Context">
<ReportNode type="Step">
<Data>
    <Name>agentName.Set</Name>
    <Description>"john"</Description>
    <StartTime>2021-06-25 11:24:17</StartTime>
    <Result>Done</Result>
    <Extension>
      <TestObject>
        <Repository>C:\Develop\git\UFT-Flight-Test-Demo\TutorialObjectRepositories\Login.tsr</Repository>
        <Path>
          <Object>
            <Type>WpfWindow</Type>
            <Name><![CDATA[Micro Focus MyFlight Sample]]></Name>
          </Object>
          <Object>
            <Type>WpfEdit</Type>
            <Name><![CDATA[agentName]]></Name>
          </Object>
        </Path>
        <Operation>Set</Operation>
        <OperationData><![CDATA["john"]]></OperationData>
        <Properties>
          <Property>
            <Name><![CDATA[devname]]></Name>
            <Value><![CDATA[agentName]]></Value>
          </Property>
        </Properties>
      </TestObject>
      <IconKey>e2248b0b4c7f45d9abbf6333f440eef0</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
    <DeviceInfo />
  </Data>
</ReportNode>
<ReportNode type="Step">
<Data>
    <Name>password.SetSecure</Name>
    <Description>"5e3ae76181a43b9140ac"</Description>
    <StartTime>2021-06-25 11:24:17</StartTime>
    <Result>Done</Result>
    <Extension>
      <TestObject>
        <Repository>C:\Develop\git\UFT-Flight-Test-Demo\TutorialObjectRepositories\Login.tsr</Repository>
        <Path>
          <Object>
            <Type>WpfWindow</Type>
            <Name><![CDATA[Micro Focus MyFlight Sample]]></Name>
          </Object>
          <Object>
            <Type>WpfEdit</Type>
            <Name><![CDATA[password]]></Name>
          </Object>
        </Path>
        <Operation>SetSecure</Operation>
        <OperationData><![CDATA["5e3ae76181a43b9140ac"]]></OperationData>
        <Properties>
          <Property>
            <Name><![CDATA[devname]]></Name>
            <Value><![CDATA[password]]></Value>
          </Property>
        </Properties>
      </TestObject>
      <IconKey>e2248b0b4c7f45d9abbf6333f440eef0</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
    <DeviceInfo />
  </Data>
</ReportNode>
<ReportNode type="Step">
<Data>
    <Name>OK.Click</Name>
    <Description />
    <StartTime>2021-06-25 11:24:17</StartTime>
    <Result>Done</Result>
    <Extension>
      <TestObject>
        <Repository>C:\Develop\git\UFT-Flight-Test-Demo\TutorialObjectRepositories\Login.tsr</Repository>
        <Path>
          <Object>
            <Type>WpfWindow</Type>
            <Name><![CDATA[Micro Focus MyFlight Sample]]></Name>
          </Object>
          <Object>
            <Type>WpfButton</Type>
            <Name><![CDATA[OK]]></Name>
          </Object>
        </Path>
        <Operation>Click</Operation>
        <Properties>
          <Property>
            <Name><![CDATA[text]]></Name>
            <Value><![CDATA[OK]]></Value>
          </Property>
          <Property>
            <Name><![CDATA[devname]]></Name>
            <Value><![CDATA[okButton]]></Value>
          </Property>
        </Properties>
      </TestObject>
      <IconKey>9dfedabd01574f84b1e568f24fdbff7e</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
    <DeviceInfo />
  </Data>
</ReportNode>
<Data>
    <Name>Micro Focus MyFlight Sample</Name>
    <Description>WpfWindow</Description>
    <StartTime>2021-06-25 11:24:17</StartTime>
    <Duration>0</Duration>
    <Result>Done</Result>
    <Extension>
      <TestObject>
        <Repository>C:\Develop\git\UFT-Flight-Test-Demo\TutorialObjectRepositories\Login.tsr</Repository>
        <Path>
          <Object>
            <Type>WpfWindow</Type>
            <Name><![CDATA[Micro Focus MyFlight Sample]]></Name>
          </Object>
        </Path>
        <OperationData><![CDATA[WpfWindow]]></OperationData>
        <Properties>
          <Property>
            <Name><![CDATA[wpftypename]]></Name>
            <Value><![CDATA[window]]></Value>
          </Property>
          <Property>
            <Name><![CDATA[regexpwndtitle]]></Name>
            <Value><![CDATA[Micro Focus MyFlight Sample Application]]></Value>
          </Property>
          <Property>
            <Name><![CDATA[devname]]></Name>
            <Value><![CDATA[Micro Focus MyFlight Sample Application]]></Value>
          </Property>
        </Properties>
      </TestObject>
      <IconKey>36839c1fc766466280f88e061c662ceb</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
  </Data>
</ReportNode>
<Data>
    <Name>Login</Name>
    <Description />
    <StartTime>2021-06-25 11:24:16</StartTime>
    <Duration>1</Duration>
    <Result>Done</Result>
    <InputParameters />
    <Extension>
      <IconKey>1e5f548f6ab24bf8b7f8b5978c10bfc9</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
  </Data>
</ReportNode>
<ReportNode type="Action">
<ReportNode type="Context">
<ReportNode type="Step">
<Data>
    <Name>fromCity.Select</Name>
    <Description>"Los Angeles"</Description>
    <StartTime>2021-06-25 11:24:17</StartTime>
    <Result>Done</Result>
    <Extension>
      <TestObject>
        <Repository>C:\Develop\git\UFT-Flight-Test-Demo\TutorialObjectRepositories\FlightFinder.tsr</Repository>
        <Path>
          <Object>
            <Type>WpfWindow</Type>
            <Name><![CDATA[Micro Focus MyFlight Sample]]></Name>
          </Object>
          <Object>
            <Type>WpfComboBox</Type>
            <Name><![CDATA[fromCity]]></Name>
          </Object>
        </Path>
        <Operation>Select</Operation>
        <OperationData><![CDATA["Los Angeles"]]></OperationData>
        <Properties>
          <Property>
            <Name><![CDATA[devname]]></Name>
            <Value><![CDATA[fromCity]]></Value>
          </Property>
        </Properties>
      </TestObject>
      <IconKey>4b152b85d3ea4708bee20abf5681d929</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
    <DeviceInfo />
  </Data>
</ReportNode>
<ReportNode type="Step">
<Data>
    <Name>toCity.Select</Name>
    <Description>"Sydney"</Description>
    <StartTime>2021-06-25 11:24:18</StartTime>
    <Result>Done</Result>
    <Extension>
      <TestObject>
        <Repository>C:\Develop\git\UFT-Flight-Test-Demo\TutorialObjectRepositories\FlightFinder.tsr</Repository>
        <Path>
          <Object>
            <Type>WpfWindow</Type>
            <Name><![CDATA[Micro Focus MyFlight Sample]]></Name>
          </Object>
          <Object>
            <Type>WpfComboBox</Type>
            <Name><![CDATA[toCity]]></Name>
          </Object>
        </Path>
        <Operation>Select</Operation>
        <OperationData><![CDATA["Sydney"]]></OperationData>
        <Properties>
          <Property>
            <Name><![CDATA[devname]]></Name>
            <Value><![CDATA[toCity]]></Value>
          </Property>
        </Properties>
      </TestObject>
      <IconKey>4b152b85d3ea4708bee20abf5681d929</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
    <DeviceInfo />
  </Data>
</ReportNode>
<ReportNode type="Step">
<Data>
    <Name>datePicker.SetDate</Name>
    <Description>#05.07.2021 11:24:18#</Description>
    <StartTime>2021-06-25 11:24:18</StartTime>
    <Result>Done</Result>
    <Extension>
      <TestObject>
        <Repository>C:\Develop\git\UFT-Flight-Test-Demo\TutorialObjectRepositories\FlightFinder.tsr</Repository>
        <Path>
          <Object>
            <Type>WpfWindow</Type>
            <Name><![CDATA[Micro Focus MyFlight Sample]]></Name>
          </Object>
          <Object>
            <Type>WpfCalendar</Type>
            <Name><![CDATA[datePicker]]></Name>
          </Object>
        </Path>
        <Operation>SetDate</Operation>
        <OperationData><![CDATA[#05.07.2021 11:24:18#]]></OperationData>
        <Properties>
          <Property>
            <Name><![CDATA[devname]]></Name>
            <Value><![CDATA[datePicker]]></Value>
          </Property>
        </Properties>
      </TestObject>
      <IconKey>18ba71abbe634d5aa41687639f0bf5ee</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
    <DeviceInfo />
  </Data>
</ReportNode>
<ReportNode type="Step">
<Data>
    <Name>Class.Select</Name>
    <Description>"Business"</Description>
    <StartTime>2021-06-25 11:24:18</StartTime>
    <Result>Done</Result>
    <Extension>
      <TestObject>
        <Repository>C:\Develop\git\UFT-Flight-Test-Demo\TutorialObjectRepositories\FlightFinder.tsr</Repository>
        <Path>
          <Object>
            <Type>WpfWindow</Type>
            <Name><![CDATA[Micro Focus MyFlight Sample]]></Name>
          </Object>
          <Object>
            <Type>WpfComboBox</Type>
            <Name><![CDATA[Class]]></Name>
          </Object>
        </Path>
        <Operation>Select</Operation>
        <OperationData><![CDATA["Business"]]></OperationData>
        <Properties>
          <Property>
            <Name><![CDATA[wpftypename]]></Name>
            <Value><![CDATA[combo box]]></Value>
          </Property>
          <Property>
            <Name><![CDATA[devname]]></Name>
            <Value><![CDATA[Class]]></Value>
          </Property>
        </Properties>
      </TestObject>
      <IconKey>4b152b85d3ea4708bee20abf5681d929</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
    <DeviceInfo />
  </Data>
</ReportNode>
<ReportNode type="Step">
<Data>
    <Name>numOfTickets.Select</Name>
    <Description>"2"</Description>
    <StartTime>2021-06-25 11:24:18</StartTime>
    <Result>Done</Result>
    <Extension>
      <TestObject>
        <Repository>C:\Develop\git\UFT-Flight-Test-Demo\TutorialObjectRepositories\FlightFinder.tsr</Repository>
        <Path>
          <Object>
            <Type>WpfWindow</Type>
            <Name><![CDATA[Micro Focus MyFlight Sample]]></Name>
          </Object>
          <Object>
            <Type>WpfComboBox</Type>
            <Name><![CDATA[numOfTickets]]></Name>
          </Object>
        </Path>
        <Operation>Select</Operation>
        <OperationData><![CDATA["2"]]></OperationData>
        <Properties>
          <Property>
            <Name><![CDATA[devname]]></Name>
            <Value><![CDATA[numOfTickets]]></Value>
          </Property>
        </Properties>
      </TestObject>
      <IconKey>4b152b85d3ea4708bee20abf5681d929</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
    <DeviceInfo />
  </Data>
</ReportNode>
<ReportNode type="Step">
<Data>
    <Name>FIND FLIGHTS.Click</Name>
    <Description />
    <StartTime>2021-06-25 11:24:18</StartTime>
    <Result>Done</Result>
    <Extension>
      <TestObject>
        <Repository>C:\Develop\git\UFT-Flight-Test-Demo\TutorialObjectRepositories\FlightFinder.tsr</Repository>
        <Path>
          <Object>
            <Type>WpfWindow</Type>
            <Name><![CDATA[Micro Focus MyFlight Sample]]></Name>
          </Object>
          <Object>
            <Type>WpfButton</Type>
            <Name><![CDATA[FIND FLIGHTS]]></Name>
          </Object>
        </Path>
        <Operation>Click</Operation>
        <Properties>
          <Property>
            <Name><![CDATA[text]]></Name>
            <Value><![CDATA[FIND FLIGHTS]]></Value>
          </Property>
          <Property>
            <Name><![CDATA[devname]]></Name>
            <Value><![CDATA[FIND FLIGHTS]]></Value>
          </Property>
        </Properties>
      </TestObject>
      <IconKey>9dfedabd01574f84b1e568f24fdbff7e</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
    <DeviceInfo />
  </Data>
</ReportNode>
<Data>
    <Name>Micro Focus MyFlight Sample</Name>
    <Description>WpfWindow</Description>
    <StartTime>2021-06-25 11:24:17</StartTime>
    <Duration>1</Duration>
    <Result>Done</Result>
    <Extension>
      <TestObject>
        <Repository>Local</Repository>
        <Path>
          <Object>
            <Type>WpfWindow</Type>
            <Name><![CDATA[Micro Focus MyFlight Sample]]></Name>
          </Object>
        </Path>
        <OperationData><![CDATA[WpfWindow]]></OperationData>
        <Properties>
          <Property>
            <Name><![CDATA[wpftypename]]></Name>
            <Value><![CDATA[window]]></Value>
          </Property>
          <Property>
            <Name><![CDATA[regexpwndtitle]]></Name>
            <Value><![CDATA[Micro Focus MyFlight Sample Application]]></Value>
          </Property>
          <Property>
            <Name><![CDATA[devname]]></Name>
            <Value><![CDATA[Micro Focus MyFlight Sample Application]]></Value>
          </Property>
        </Properties>
      </TestObject>
      <IconKey>36839c1fc766466280f88e061c662ceb</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
  </Data>
</ReportNode>
<Data>
    <Name>FlightFinder</Name>
    <Description />
    <StartTime>2021-06-25 11:24:17</StartTime>
    <Duration>1</Duration>
    <Result>Done</Result>
    <InputParameters />
    <Extension>
      <IconKey>1e5f548f6ab24bf8b7f8b5978c10bfc9</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
  </Data>
</ReportNode>
<ReportNode type="Action">
<ReportNode type="Context">
<ReportNode type="Step">
<Data>
    <Name>flightsDataGrid.SelectCell</Name>
    <Description>"0", "0"</Description>
    <StartTime>2021-06-25 11:24:19</StartTime>
    <Result>Done</Result>
    <Extension>
      <TestObject>
        <Repository>C:\Develop\git\UFT-Flight-Test-Demo\TutorialObjectRepositories\SelectFlight.tsr</Repository>
        <Path>
          <Object>
            <Type>WpfWindow</Type>
            <Name><![CDATA[Micro Focus MyFlight Sample]]></Name>
          </Object>
          <Object>
            <Type>WpfTable</Type>
            <Name><![CDATA[flightsDataGrid]]></Name>
          </Object>
        </Path>
        <Operation>SelectCell</Operation>
        <OperationData><![CDATA["0", "0"]]></OperationData>
        <Properties>
          <Property>
            <Name><![CDATA[devname]]></Name>
            <Value><![CDATA[flightsDataGrid]]></Value>
          </Property>
        </Properties>
      </TestObject>
      <IconKey>9c28078cb1e74639ae1d17c1dfeeb6f5</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
    <DeviceInfo />
  </Data>
</ReportNode>
<ReportNode type="Step">
<Data>
    <Name>SELECT FLIGHT.Click</Name>
    <Description />
    <StartTime>2021-06-25 11:24:19</StartTime>
    <Result>Done</Result>
    <Extension>
      <TestObject>
        <Repository>C:\Develop\git\UFT-Flight-Test-Demo\TutorialObjectRepositories\SelectFlight.tsr</Repository>
        <Path>
          <Object>
            <Type>WpfWindow</Type>
            <Name><![CDATA[Micro Focus MyFlight Sample]]></Name>
          </Object>
          <Object>
            <Type>WpfButton</Type>
            <Name><![CDATA[SELECT FLIGHT]]></Name>
          </Object>
        </Path>
        <Operation>Click</Operation>
        <Properties>
          <Property>
            <Name><![CDATA[text]]></Name>
            <Value><![CDATA[SELECT FLIGHT]]></Value>
          </Property>
          <Property>
            <Name><![CDATA[devname]]></Name>
            <Value><![CDATA[selectFlightBtn]]></Value>
          </Property>
        </Properties>
      </TestObject>
      <IconKey>9dfedabd01574f84b1e568f24fdbff7e</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
    <DeviceInfo />
  </Data>
</ReportNode>
<Data>
    <Name>Micro Focus MyFlight Sample</Name>
    <Description>WpfWindow</Description>
    <StartTime>2021-06-25 11:24:19</StartTime>
    <Duration>0</Duration>
    <Result>Done</Result>
    <Extension>
      <TestObject>
        <Repository>C:\Develop\git\UFT-Flight-Test-Demo\TutorialObjectRepositories\SelectFlight.tsr</Repository>
        <Path>
          <Object>
            <Type>WpfWindow</Type>
            <Name><![CDATA[Micro Focus MyFlight Sample]]></Name>
          </Object>
        </Path>
        <OperationData><![CDATA[WpfWindow]]></OperationData>
        <Properties>
          <Property>
            <Name><![CDATA[wpftypename]]></Name>
            <Value><![CDATA[window]]></Value>
          </Property>
          <Property>
            <Name><![CDATA[regexpwndtitle]]></Name>
            <Value><![CDATA[Micro Focus MyFlight Sample Application]]></Value>
          </Property>
          <Property>
            <Name><![CDATA[devname]]></Name>
            <Value><![CDATA[Micro Focus MyFlight Sample Application]]></Value>
          </Property>
        </Properties>
      </TestObject>
      <IconKey>36839c1fc766466280f88e061c662ceb</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
  </Data>
</ReportNode>
<Data>
    <Name>SelectFlight</Name>
    <Description />
    <StartTime>2021-06-25 11:24:18</StartTime>
    <Duration>1</Duration>
    <Result>Done</Result>
    <InputParameters />
    <Extension>
      <IconKey>1e5f548f6ab24bf8b7f8b5978c10bfc9</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
  </Data>
</ReportNode>
<ReportNode type="Action">
<ReportNode type="Context">
<ReportNode type="Step">
<Data>
    <Name>passengerName.Set</Name>
    <Description>"Silvio Glöckner"</Description>
    <StartTime>2021-06-25 11:24:19</StartTime>
    <Result>Done</Result>
    <Extension>
      <TestObject>
        <Repository>C:\Develop\git\UFT-Flight-Test-Demo\TutorialObjectRepositories\FlightConfirmation.tsr</Repository>
        <Path>
          <Object>
            <Type>WpfWindow</Type>
            <Name><![CDATA[Micro Focus MyFlight Sample]]></Name>
          </Object>
          <Object>
            <Type>WpfEdit</Type>
            <Name><![CDATA[passengerName]]></Name>
          </Object>
        </Path>
        <Operation>Set</Operation>
        <OperationData><![CDATA["Silvio Glöckner"]]></OperationData>
        <Properties>
          <Property>
            <Name><![CDATA[devname]]></Name>
            <Value><![CDATA[passengerName]]></Value>
          </Property>
        </Properties>
      </TestObject>
      <IconKey>e2248b0b4c7f45d9abbf6333f440eef0</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
    <DeviceInfo />
  </Data>
</ReportNode>
<ReportNode type="Step">
<Data>
    <Name>ORDER.Click</Name>
    <Description />
    <StartTime>2021-06-25 11:24:19</StartTime>
    <Result>Done</Result>
    <Extension>
      <TestObject>
        <Repository>C:\Develop\git\UFT-Flight-Test-Demo\TutorialObjectRepositories\FlightConfirmation.tsr</Repository>
        <Path>
          <Object>
            <Type>WpfWindow</Type>
            <Name><![CDATA[Micro Focus MyFlight Sample]]></Name>
          </Object>
          <Object>
            <Type>WpfButton</Type>
            <Name><![CDATA[ORDER]]></Name>
          </Object>
        </Path>
        <Operation>Click</Operation>
        <Properties>
          <Property>
            <Name><![CDATA[text]]></Name>
            <Value><![CDATA[ORDER]]></Value>
          </Property>
          <Property>
            <Name><![CDATA[devname]]></Name>
            <Value><![CDATA[orderBtn]]></Value>
          </Property>
        </Properties>
      </TestObject>
      <IconKey>9dfedabd01574f84b1e568f24fdbff7e</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
    <DeviceInfo />
  </Data>
</ReportNode>
<ReportNode type="Step">
<Data>
    <Name>progBar.WaitProperty</Name>
    <Description>"value", 100, 100, 20000</Description>
    <StartTime>2021-06-25 11:24:20</StartTime>
    <Result>Done</Result>
    <Extension>
      <TestObject>
        <Repository>C:\Develop\git\UFT-Flight-Test-Demo\TutorialObjectRepositories\FlightConfirmation.tsr</Repository>
        <Path>
          <Object>
            <Type>WpfWindow</Type>
            <Name><![CDATA[Micro Focus MyFlight Sample]]></Name>
          </Object>
          <Object>
            <Type>WpfProgressBar</Type>
            <Name><![CDATA[progBar]]></Name>
          </Object>
        </Path>
        <Operation>WaitProperty</Operation>
        <OperationData><![CDATA["value", 100, 100, 20000]]></OperationData>
        <Properties>
          <Property>
            <Name><![CDATA[devname]]></Name>
            <Value><![CDATA[progBar]]></Value>
          </Property>
        </Properties>
      </TestObject>
      <IconKey>7f6e6e3758b64e3a8e14a56829bc8aaa</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
    <DeviceInfo />
  </Data>
</ReportNode>
<ReportNode type="Step">
<Data>
    <Name>NEW SEARCH.Click</Name>
    <Description />
    <StartTime>2021-06-25 11:24:21</StartTime>
    <Result>Done</Result>
    <Extension>
      <TestObject>
        <Repository>C:\Develop\git\UFT-Flight-Test-Demo\TutorialObjectRepositories\FlightConfirmation.tsr</Repository>
        <Path>
          <Object>
            <Type>WpfWindow</Type>
            <Name><![CDATA[Micro Focus MyFlight Sample]]></Name>
          </Object>
          <Object>
            <Type>WpfButton</Type>
            <Name><![CDATA[NEW SEARCH]]></Name>
          </Object>
        </Path>
        <Operation>Click</Operation>
        <Properties>
          <Property>
            <Name><![CDATA[text]]></Name>
            <Value><![CDATA[NEW SEARCH]]></Value>
          </Property>
          <Property>
            <Name><![CDATA[devname]]></Name>
            <Value><![CDATA[newSearchBtn]]></Value>
          </Property>
        </Properties>
      </TestObject>
      <IconKey>9dfedabd01574f84b1e568f24fdbff7e</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
    <DeviceInfo />
  </Data>
</ReportNode>
<Data>
    <Name>Micro Focus MyFlight Sample</Name>
    <Description>WpfWindow</Description>
    <StartTime>2021-06-25 11:24:19</StartTime>
    <Duration>2</Duration>
    <Result>Done</Result>
    <Extension>
      <TestObject>
        <Repository>C:\Develop\git\UFT-Flight-Test-Demo\TutorialObjectRepositories\FlightConfirmation.tsr</Repository>
        <Path>
          <Object>
            <Type>WpfWindow</Type>
            <Name><![CDATA[Micro Focus MyFlight Sample]]></Name>
          </Object>
        </Path>
        <OperationData><![CDATA[WpfWindow]]></OperationData>
        <Properties>
          <Property>
            <Name><![CDATA[wpftypename]]></Name>
            <Value><![CDATA[window]]></Value>
          </Property>
          <Property>
            <Name><![CDATA[regexpwndtitle]]></Name>
            <Value><![CDATA[Micro Focus MyFlight Sample Application]]></Value>
          </Property>
          <Property>
            <Name><![CDATA[devname]]></Name>
            <Value><![CDATA[Micro Focus MyFlight Sample Application]]></Value>
          </Property>
        </Properties>
      </TestObject>
      <IconKey>36839c1fc766466280f88e061c662ceb</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
  </Data>
</ReportNode>
<Data>
    <Name>FlightConfirmation</Name>
    <Description />
    <StartTime>2021-06-25 11:24:19</StartTime>
    <Duration>2</Duration>
    <Result>Done</Result>
    <InputParameters />
    <Extension>
      <IconKey>1e5f548f6ab24bf8b7f8b5978c10bfc9</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
  </Data>
</ReportNode>
<ReportNode type="Action">
<Data>
    <Name>CloseApp</Name>
    <Description />
    <StartTime>2021-06-25 11:24:21</StartTime>
    <Result>Done</Result>
    <InputParameters />
    <Extension>
      <IconKey>1e5f548f6ab24bf8b7f8b5978c10bfc9</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
  </Data>
</ReportNode>
<Data>
    <Name>MyFlight</Name>
    <ToolName>Micro Focus Unified Functional Testing</ToolName>
    <ToolVersion>0</ToolVersion>
    <ToolVersionStringLiteral>15.0.2</ToolVersionStringLiteral>
    <Description />
    <StartTime>2021-06-25 11:24:14</StartTime>
    <Duration>7</Duration>
    <Result>Done</Result>
    <InputParameters />
    <Extension>
      <IconKey>e1df9a1ddffc4fbfa01051c4f9be10a2</IconKey>
      <IsPlainTextNodeName>True</IsPlainTextNodeName>
    </Extension>
    <Environment>
      <Timezone>+02:00:00</Timezone>
      <Locale>Deutsch (Deutschland)</Locale>
      <User>AD\sgloeckner</User>
      <CpuInfo>Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz</CpuInfo>
      <NumberOfCores>12</NumberOfCores>
      <TotalMemory>32514</TotalMemory>
      <HostName>ad.proficom.de\P0002-WIN10-SG</HostName>
      <OSInfo>Windows 10</OSInfo>
    </Environment>
    <TestedApplications />
    <Links>
      <Link type="DataTable" reference="Default.xlsx" displayname="Default Data Table" />
    </Links>
  </Data>
</ReportNode>
<GeneralInfo>
    <ResultName>Report12</ResultName>
    <RunStartTime>2021-06-25 11:24:14</RunStartTime>
    <Timezone>+02:00:00</Timezone>
    <OrchestrationToolName>Micro Focus Unified Functional Testing</OrchestrationToolName>
    <OrchestrationToolVersion>0</OrchestrationToolVersion>
    <OrchestrationToolVersionStringLiteral>15.0.2</OrchestrationToolVersionStringLiteral>
  </GeneralInfo>
</Results>`

**Comment by soleverxu** [comment]
Fixed in the `v1.0 beta (rev.7)` release. Please download the executable file in the release page.

**Comment by metaph3r** [comment]
Thanks. The conversion is working again.
